### ISSUE TITLE
`npm init` creates empty package on Windows

### ISSUE THREAD

**Issue by phenomen** [svelteness/kit-docs#11]
`npm init @svelteness/kit-docs mydocs`

```
PS D:\Github\lancer-docs> npm init @svelteness/kit-docs mydocs

√ Default KitDocs Theme? (Y/n) · true

[kit-docs]: target directory is empty, creating new SvelteKit app.

PS D:\Github\lancer-docs>
```

Nothing happens, folder is empty.

**Comment by mihar-22** [comment]
Ah this is a Windows specific bug. Tough to debug because I don't have a dev environment on a Windows machine. Best bet would be for you, or someone who has time to do the following and help me debug it:

- `git clone git@github.com:svelteness/kit-docs.git`
- `cd kit-docs`
- `pnpm i` (install [PNPM](https://pnpm.io/installation) if you don't have it)
- `node ./packages/create-kit-docs/bin/create-kit-docs.js test` (runs create package locally)

Next steps are more ambigious because we need to walk through the script (again at `./packages/create-kit-docs/bin/create-kit-docs-js `) and figure out what's wrong. Probaby [start here](https://github.com/svelteness/kit-docs/blob/main/packages/create-kit-docs/bin/create-kit-docs.js#L37-L53) since it's where it stops.

**Comment by phenomen** [comment]
Test run:
```
PS D:\Github\lancer> node ./packages/create-kit-docs/bin/create-kit-docs.js test

√ Default KitDocs Theme? (Y/n) · true

[kit-docs]: target directory is empty, creating new SvelteKit app.

[kit-docs]: failed to create new app.

Error: spawn npm ENOENT
```

**Comment by mihar-22** [comment]
Thanks heaps @phenomen!
