### ISSUE TITLE
I propose to pin @sveltejs/adapter-auto and @sveltejs/kit version in create-kit-docs script

### ISSUE THREAD

**Issue by stephane-klein** [svelteness/kit-docs#50]
Hi,

@mihar-22 What do you think about pin `@sveltejs/adapter-auto` and `@sveltejs/kit` version [here](https://github.com/svelteness/kit-docs/blob/e4b20bc1d9eb4e2898def10fc583f0bc495f60ef/packages/create-kit-docs/bin/create-kit-docs.js#L95) to avoid some version errors like https://github.com/svelteness/kit-docs/issues/48 ?

Best regards,
Stéphane

**Comment by mihar-22** [comment]
We'll just need to update KitDocs to match the latest SvelteKit. Things are changing quickly as they're working towards 1.0 and I'm a little busy to keep up. If anyone opens a PR that does that I'll happily pull it in @stephane-klein :)

**Comment by stephane-klein** [comment]
@mihar-22 thanks ! :+1:

Question: do you think it's a bad idea to pin versions? I think that it would save `kit-docs` users (like me) a lot of trouble in case of SvelteKit breaking change.

**Comment by mihar-22** [comment]
No problem!

I think you can cause trouble by both pinning and not. I think we have to just look at the likelihood of breaking changes occurring. I don't really see anything else breaking KitDocs because we're working with the very core of SvelteKit (mainly routing and endpoints). The recent CLI and Vite config change was a good thing for the ecosystem and is an example of a core change that won't really happen often.

I think if we find that it's breaking often we can definitely pin it until 1.0 :)

**Comment by stephane-klein** [comment]
> If we find that it's breaking often we can definitely pin it until 1.0 :)

@mihar-22 ok, I understand, we will maybe pin it the next time 🙂

**Comment by stephane-klein** [comment]
@mihar-22 There are another breaking change #52, I think that `vite` version must be pinned.
