### ISSUE TITLE
migrate to latest sveltekit 

### ISSUE THREAD

**Issue by mihar-22** [svelteness/kit-docs#70]
Re-opening as a new issue (continuation of this [PR](https://github.com/svelteness/kit-docs/pull/69)) because I was unable to fix the Vite server repeatedly restarting. On top of that I can't release because of a bunch of TS issues as few things in SvelteKit are not playing nice with API Extractor.

This migration has been a huge pain and because of my super limited time it's hard to work through it. If anyone wants to have an attempt at fixing it there are some intstructions in linked PR above. The type issues can be seen if run `npm run build`.

**Comment by joshnuss** [comment]
Maybe try running vite with debug enabled: 

```sh
DEBUG=vite:* pnpm dev
```

**Comment by luke-hagar-sp** [comment]
Hey @mihar-22, 

I would REALLY love to contribute here, and to the project as a whole, do you have any place that development of this project can be discussed, A discord server, slack channel, or discussions here on GitHub?

I am extremely interested in the goal here, and there is so much potential in this project, I'm going to take a look under the hood at this PR and see if I can help at all, but otherwise is there anything specific you want help with?

**Comment by mihar-22** [comment]
We're now officially working with SvelteKit 1.0!!!!!!!!!!!

Thank you so much to:

- @slowsage
- @davej
- @carstenlebek 

❤️
